# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "A simple terminal UI to manage your git stash"
  homepage "https://github.com/fkhadra/stash/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fkhadra/stash/releases/download/v0.0.1/stash_0.0.1_Darwin_arm64.tar.gz"
      sha256 "77cff499a7f12a4c8d0d56e1218849bf4003cedad965178e959e8754840d81dd"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fkhadra/stash/releases/download/v0.0.1/stash_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "2bf26dade438b2c643f0c9efe4d3da4b78cfc1b4684c0eaca6eacd8654408727"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fkhadra/stash/releases/download/v0.0.1/stash_0.0.1_Linux_armv6.tar.gz"
      sha256 "ff3373c56531e4b376c942a46557efaed92e3216626cb1e855b33dcfe6c82963"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fkhadra/stash/releases/download/v0.0.1/stash_0.0.1_Linux_arm64.tar.gz"
      sha256 "73e0677e0ccc8c06c06be75c40639afe8e357a1cdd7a49de42f36be2631304da"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fkhadra/stash/releases/download/v0.0.1/stash_0.0.1_Linux_x86_64.tar.gz"
      sha256 "1627aea0ea89d13a0405963095ebef13c4655c00ffcf2ed4b841170a3a015f23"

      def install
        bin.install "stash"
      end
    end
  end
end
